#! /bin/bash

export PATH="/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin:/sbin:/bin"

header='test -f /data1/jenkins_home/.jenkins/workspace/shell/settings && . /data1/jenkins_home/.jenkins/workspace/shell/settings || exit 1'
script="$2"

sed -i "1 i$header" $script
/bin/bash -xe $script
